import Head from "next/head";
import Image from "next/image";
import HeaderNoAuth from "../components/HeaderNoAuth";

export default function Home() {
  return (
    <div className={`h-screen bg-gray-800`}>
      <Head>
        <title>Workout ViZ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <HeaderNoAuth />
        <div className="">{/* //welcomebody */}</div>
      </div>
    </div>
  );
}
